blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogPostListView, BlogPostDetailView, BlogPostCreateView, BlogPostUpdateView, BlogPostDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('', BlogPostListView.as_view(), name='blog_list'),
    path('detail/<slug>/', cache_page(60)(BlogPostDetailView.as_view()), name='blog_detail'),
    path('create/', BlogPostCreateView.as_view(), name='blog_create'),
    path('update/<slug>/', BlogPostUpdateView.as_view(), name='blog_update'),
    path('delete/<slug>/', BlogPostDeleteView.as_view(), name='blog_delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('client/', include('message_email.urls', namespace='client')),
    path('email/', include('message_email.urls', namespace='email')),
    path('users/', include('users.urls', namespace='users')),
    path("blog/", include("blog.urls", namespace="blog")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

message_email/urls.py
from django.urls import path

from message_email.apps import MessageEmailConfig
from message_email.views import MessageListView, MessageCreateView, MessageUpdateView, MessageDeleteView, \
    MailingListView

app_name = MessageEmailConfig.name

urlpatterns = [
    path('mailings/', MailingListView.as_view(), name='mailing_list'),
    path('messages/', MessageListView.as_view(), name='message_list'),
    path('messages/create/', MessageCreateView.as_view(), name='message_create'),
    path('update/<int:pk>/', MessageUpdateView.as_view(), name='message_update'),
    path('delete/<int:pk>/', MessageDeleteView.as_view(), name='message_delete'),

]

message_email/models.py
from django.db import models

from home.models import HomeClient
from users.models import User

NULLABLE = {'blank': True, 'null': True}


class Message(models.Model):
    TIME_CHOICES = (
        ('daily', 'Раз в день'),
        ('weekly', 'Раз в неделю'),
        ('monthly', 'Раз в месяц'),
    )

    STATUS_CHOICES = (
        ('created', 'Создана'),
        ('launched', 'Запущена'),
        ('finished', 'Завершена'),
    )

    start_time = models.TimeField(null=True, blank=True)
    end_time = models.TimeField(null=True, blank=True)
    send_datetime = models.DateTimeField(verbose_name='Время и дата рассылки', **NULLABLE)
    frequency = models.CharField(max_length=10, choices=TIME_CHOICES)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default=STATUS_CHOICES,
                              verbose_name='Статус')
    send_from_user = models.ForeignKey(User, on_delete=models.CASCADE, **NULLABLE, related_name='user',
                                       verbose_name='Отправитель')

    send_to_client = models.ManyToManyField(to='home.HomeClient', related_name='client',
                                            verbose_name='Получатель')
    is_active = models.BooleanField(default=True, verbose_name='Активен')
    """
    Сообщение для рассылки.
    """
    subject = models.CharField(max_length=255, verbose_name='Тема письма')
    message = models.TextField(verbose_name='Сообщение')

    def __str__(self):
        return f"Сообщение {self.subject}"

    class Meta:
        permissions = [
            ("Can_view_any_newsletters", 'Can view any mailings'),
            ("You_can_disable_newsletters", 'Can disable mailings'),
            ("They_cannot_edit_mailings.", 'Cannot edit mailings.'),
            ("Can't_manage_the_mailing_list", 'Cannot manage mailing list'),
            ("Cannot_change_mailings_and_messages", 'Cannot change mailings and messages'),
        ]
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'


class EmailLog(models.Model):
    mailing = models.ForeignKey(Message, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True, verbose_name='время последней попытки')
    status = models.CharField(max_length=20)
    server_response = models.TextField(**NULLABLE, verbose_name='ответ почтового сервера')

    def __str__(self):
        return f"Лог рассылки {self.mailing}"

    class Meta:
        verbose_name = 'Логи рассылка'
        verbose_name_plural = 'Логи рассылки'

message_email/forms.py
from datetime import datetime, timedelta

from django import forms
from django.core.exceptions import ValidationError
from django.utils.timezone import make_aware

from home.models import HomeClient
from .models import Message


class MessageForm(forms.ModelForm):
    """Форма для электронной почты использует виджеты классов начальной загрузки и проверяет некоторые поля."""

    class Meta:
        model = Message
        fields = (
            'subject', 'message', 'send_to_client', 'frequency', 'status', 'send_datetime', 'is_active',)

        widgets = {
            'send_datetime': forms.DateTimeInput(
                attrs={"class": "form-control", 'type': 'datetime-local'})
        }

    def __init__(self, *args, **kwargs):
        # in CreateView we added user = self.request.user
        user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)

        if user:
            self.fields['send_to_client'].queryset = HomeClient.objects.filter(user=user)

        self.fields['subject'].widget.attrs.update(
            {"class": "form-control", "placeholder": "Напишите тему письма"})
        self.fields['message'].widget.attrs.update(
            {"class": "form-control", "rows": 5, "placeholder": "Напишите свое сообщение"})
        self.fields['frequency'].widget.attrs.update(
            {"class": "form-control"})
        self.fields['status'].widget.attrs.update(
            {"class": "form-control"})
        self.fields['send_to_client'].widget.attrs.update(
            {"class": "form-control"})

    # def clean_send_datetime(self):
    #     send_datetime = self.cleaned_data['send_datetime']
    #     cur_datetime = datetime.now() + timedelta(hours=5)
    #
    #     if send_datetime < cur_datetime:
    #         raise ValidationError("Вы не можете отправлять электронные письма в прошлом.")
    #
    #     return send_datetime

    def clean(self):
        """Преобразует дату и время в правильный формат."""
        cleaned_data = super().clean()
        send_date = cleaned_data.get('send_date')
        if send_date:
            cleaned_data['send_date'] = make_aware(send_date)
        return cleaned_data

message_email/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, TemplateView

from message_email.forms import MessageForm
from message_email.models import Message


class MailingListView(TemplateView):
    template_name = 'message_email/mailing_list.html'
    extra_context = {
        'title': 'Наши рассылки'
    }

    def get_queryset(self):
        """Отображает конкретные письма в зависимости от того, кто является пользователем запроса."""
        if self.request.user.is_superuser or self.request.user.groups.filter(name='manager').exists():
            return Message.objects.all()
        return Message.objects.filter(send_from_user=self.request.user)


class MessageListView(LoginRequiredMixin, ListView):
    model = Message
    template_name = 'message_email/message_list.html'
    permission_required = []
    extra_context = {
        'title': 'Список рассылок'
    }

    def get_queryset(self):
        """Отображает конкретные письма в зависимости от того, кто является пользователем запроса."""
        if self.request.user.is_superuser or self.request.user.groups.filter(name='manager').exists():
            return Message.objects.all()
        return Message.objects.filter(send_from_user=self.request.user)


class MessageCreateView(LoginRequiredMixin, CreateView):
    model = Message
    form_class = MessageForm
    template_name = 'message_email/message_form.html'
    success_url = reverse_lazy('email:message_list')

    def get_form_kwargs(self):
        """Отправляем id пользователя в form.py, чтобы мы могли показывать только клиентов этого пользователя."""
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        """Сохранение электронного письма с id пользователя из запроса"""
        if form.is_valid():
            form.instance.send_from_user = self.request.user
            form.save()
        return super().form_valid(form)


class MessageUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Message
    form_class = MessageForm
    template_name = 'message_email/message_form.html'
    success_url = reverse_lazy('email:message_list')
    permission_required = []

    def has_permission(self):
        """Предоставляет разрешение по конкретному запросу пользователей."""
        email = self.get_object()
        if self.request.user == email.send_from_user or self.request.user.groups.filter(name='manager').exists():
            return True
        if self.request.user == email.send_to_user:
            return True
        return super().has_permission()

    def get_form_kwargs(self):
        """Отправляет id пользователя в form.py, чтобы мы могли показывать только клиентов этого пользователя."""
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def get_form_class(self):
        """Отображает конкретную форму в зависимости от того, кто является пользователем запроса."""
        if self.request.user == self.object.send_from_user or self.request.user.groups.filter(name='manager').exists():
            return MessageForm
        elif self.request.user == self.object.send_from_user:
            return MessageForm
        else:
            return None


class MessageDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Message
    template_name = 'message_email/message_confirm_delete.html'
    success_url = reverse_lazy('email:message_list')
    permission_required = []

    def has_permission(self):
        """Предоставляет разрешение по конкретному запросу пользователей."""
        email = self.get_object()
        if self.request.user == email.send_from_user:
            return super().has_permission()

message_email/templates/message_email/mailing_list.html
{% extends 'home/base.html' %}

{% block content %}
    <div class="container-fluid py-5">
        <div class="row justify-content-center">
            <div class="col-md-6 text-center">
                <a href="{% url 'email:message_create' %}" class="btn btn-light btn-outline-info text-dark">
                    Добавить рассылку
                </a>
            </div>
        </div>
    </div>

{% endblock content %}

message_email/templates/message_email/message_confirm_delete.html
{% extends 'home/base.html' %}

{% block content %}
    <div class="container d-flex justify-content-center align-items-center h-50">
        <div class="card text-center" style="max-width: 18rem;">
            <div class="card-header bg-danger text-white">
                Подтвердить удаление
            </div>
            <div class="card-body">
                <p class="card-text">
                    Вы уверены, что хотите удалить это письмо: {{ mail.subject }}?
                </p>
                <form method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-sm btn-danger me-2">
                        Подтвердить
                    </button>
                    <a href="{% url 'email:message_list' %}" class="btn btn-sm btn-secondary">
                        Отмена
                    </a>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

message_email/templates/message_email/message_form.html
{% extends 'home/base.html' %}

{% block content %}
    <div class="d-flex justify-content-center align-items-center pt-5">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-6 col-md-8 col-sm-10">
                    <div class="card shadow-lg p-4">
                        <h4 class="text-center mb-4">
                            {% if object %}
                                Редактировать адрес e-mail
                            {% else %}
                                Добавьте свой адрес электронной почты
                            {% endif %}
                        </h4>
                        <form method="post">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <div class="d-flex justify-content-center">
                                <button type="submit" class="btn btn-sm btn-outline-secondary text-danger">Сохранить
                                </button>
                                <a href="{% url 'email:message_list' %}" class="btn btn-sm btn-secondary">Отмена</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

message_email/templates/message_email/message_list.html
{% extends 'home/base.html' %}

{% block content %}
    <div class="container-fluid py-5">
        <div class="row justify-content-center">
            <div class="col-md-6 text-center">
                <a href="{% url 'email:message_create' %}" class="btn btn-light btn-outline-info text-dark">
                    Добавить рассылку
                </a>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row">
            {% for mail in object_list %}
                <div class="col-lg-4 col-md-6 col-sm-12 mb-4">
                    <div class="card {% cycle 'bg-sm' 'bg-sm' as color %} text-dark shadow">
                        <div class="card-header text-center"><h5>{{ mail.subject }}</h5></div>
                        <div class="card-body ">
                            <p>Сообщение: {{ mail.message|truncatechars:35 }}</p>
                            <p class="card-text">Получатель:
                                {% for client in mail.send_to_client.all|slice:2 %}
                                    {{ client.full_name }}
                                    {% if not forloop.last %},
                                    {% endif %}
                                    {% if forloop.last %}{% endif %}
                                {% endfor %}
                            </p>
                            <p class="card-text">Дата: {{ mail.send_datetime }}</p>
                            <p class="mb-0">Чистота: {{ mail.get_frequency_display }}</p>

                            <div class="d-flex justify-content-between align-items-center mt-3">
                                <p class="card-text">Статус: {{ mail.get_status_display }}</p>
                                <div>
                                    <a href="{% url 'email:message_update' mail.id %}"
                                       class="btn btn-sm {% if color == 'bg-dark' %}btn-secondary{% else %}btn-dark{% endif %} text-white">Edit</a>
                                    <a href="{% url 'email:message_delete' mail.id %}"
                                       class="btn btn-sm ms-1 {% if color == 'bg-danger' %}btn-secondary{% else %}btn-danger{% endif %} text-white">Delete</a>
                                </div>
                            </div>
                        </div>
                        <div class="card-footer bg-transparent border-0"></div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock content %}