blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogPostListView, BlogPostDetailView, BlogPostCreateView, BlogPostUpdateView, BlogPostDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('', BlogPostListView.as_view(), name='blog_list'),
    path('detail/<slug>/', cache_page(60)(BlogPostDetailView.as_view()), name='blog_detail'),
    path('create/', BlogPostCreateView.as_view(), name='blog_create'),
    path('update/<slug>/', BlogPostUpdateView.as_view(), name='blog_update'),
    path('delete/<slug>/', BlogPostDeleteView.as_view(), name='blog_delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('client/', include('message_email.urls', namespace='client')),
    path('email/', include('message_email.urls', namespace='email')),
    path('users/', include('users.urls', namespace='users')),
    path("blog/", include("blog.urls", namespace="blog")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.conf import settings
from django.db import models
from django.template.defaultfilters import slugify

NULLABLE = {'blank': True, 'null': True}


class BlogPost(models.Model):
    title = models.CharField(max_length=100, verbose_name='Заголовок')
    slug = models.SlugField(unique=True, max_length=100)
    content = models.TextField(**NULLABLE, verbose_name='Содержимое статьи')
    preview_image = models.ImageField(upload_to='blog_images/', **NULLABLE, verbose_name='Изображение')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    is_published = models.BooleanField(default=True, verbose_name='Опубликовано')
    views_count = models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = "Статья"
        verbose_name_plural = "Статьи"

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from django.utils.text import slugify

from blog.models import BlogPost


class BlogPostCreateView(LoginRequiredMixin, CreateView):
    model = BlogPost
    fields = ('title', 'content', 'preview_image')
    success_url = reverse_lazy('blog:blog_list')
    extra_context = {
        'title': 'Добавить новую статью'
    }

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.owner = self.request.user
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()
        return super().form_valid(form)


class BlogPostListView(ListView):
    model = BlogPost
    extra_context = {
        'title': 'Список статей'
    }

    def get_queryset(self, *args, **kwargs):
        queryset = BlogPost.objects.filter(is_published=True)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        user_group_names = [group.name for group in user.groups.all()]
        context['user_group_names'] = user_group_names
        return context


class BlogPostDetailView(DetailView):
    model = BlogPost
    extra_context = {
        'title': 'Содержание'
    }

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class BlogPostUpdateView(LoginRequiredMixin, UpdateView):
    model = BlogPost
    fields = ('title', 'content', 'preview_image')
    extra_context = {
        'title': 'Редактировать статью'
    }

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()
        return super().form_valid(form)

    def get_object(self, queryset=None):
        title = super().get_object(queryset)
        blog = get_object_or_404(BlogPost, title=title)
        user_groups = [group.name for group in self.request.user.groups.all()]
        if blog.owner != self.request.user and 'Managers' not in user_groups:
            raise Http404
        return blog

    def get_success_url(self):
        return reverse('blog:blog_detail', args=[self.kwargs.get('slug')])


class BlogPostDeleteView(LoginRequiredMixin, DeleteView):
    model = BlogPost
    success_url = reverse_lazy('blog:blog_list')
    extra_context = {
        'title': 'Удаление статьи'
    }

    def get_object(self, queryset=None):
        title = super().get_object(queryset)
        blog = get_object_or_404(BlogPost, title=title)
        user_groups = [group.name for group in self.request.user.groups.all()]
        if blog.owner != self.request.user and 'Managers' not in user_groups:
            raise Http404
        return blog

blog/templates/blog/blogpost_confirm_delete.html
{% extends 'home/base.html' %}
{% block content %}
    <div class="container d-flex justify-content-center align-items-center h-50">
        <div class="card text-center" style="max-width: 18rem;">
            <div class="card-header bg-danger text-white">
                Подтвердить удаление
            </div>
            <div class="card-body">
                <p class="card-text">
                    Вы уверены, что хотите удалить эту статью: {{ object.title }}?
                </p>
                <form method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-sm btn-outline-secondary text-danger">
                        Подтвердить
                    </button>
                    <a href="{% url 'blog:blog_list' %}" class="btn btn-sm btn-secondary">
                        Отмена
                    </a>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/blogpost_detail.html
{% extends 'home/base.html' %}

{% load my_tags %}

{% block content %}
    <div class="d-flex justify-content-center align-items-center h-50">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-6 col-md-8 col-sm-10">
                    <div class="card shadow-lg p-4">
                        <table class="table table-striped">
                            <tr class="align-self-lg-center">
                                <img class="card-img-top mb-2" style="max-width: 35%"
                                     src="{% mediafile object.preview_image %} "/>
                            </tr>
                            <tr>
                                <td class="w-25">Заголовок</td>
                                <td>{{ object.title }}</td>
                            </tr>
                            <tr>
                                <td class="w-25">Слаг</td>
                                <td>{{ object.slug }}</td>
                            </tr>
                            <tr>
                                <td class="w-25">Содержание</td>
                                <td>{{ object.content }}</td>
                            </tr>
                            <tr>
                                <td class="w-25">ID записи</td>
                                <td>{{ object.id }}</td>
                            </tr>
                            <tr>
                                <td class="w-25">Создана</td>
                                <td>{{ object.created_at }}</td>
                            </tr>
                            <tr>
                                <td class="w-25">Просмотры</td>
                                <td>{{ object.views_count }}</td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}>

blog/templates/blog/blogpost_form.html
{% extends 'home/base.html' %}
{% block content %}
    <div class="d-flex justify-content-center align-items-center h-50">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-6 col-md-8 col-sm-10">
                    <div class="card shadow-lg p-4">
                        <h1 class="text-center mb-4">
                            {% if object %}
                                Редактировать статью
                            {% else %}
                                Добавить статью
                            {% endif %}
                        </h1>
                        <form method="post">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-success w-100">
                                {% if object %}
                                    Сохранить
                                {% else %}
                                    Создать
                                {% endif %}
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/blogpost_list.html
{% extends 'home/base.html' %}

{% load my_tags %}

{% block content %}
    <div class="container-fluid py-5">
        <div class="row justify-content-center">
            <div class="col-md-6 text-center">
                <a href="{% url 'blog:blog_create' %}" class="btn btn-light btn-outline-info text-dark">
                    Добавить статью
                </a>
            </div>
        </div>
    </div>
    <div class="album py-5 bg-body-tertiary">
        <div class="container">
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                {% for item in object_list %}
                    <div class="col-3">
                        <div class="card mb-4 box-shadow">
                            <div class="card-header">
                                <h4 class="my-0 font-weight-normal">{{ item.title }}</h4>
                            </div>
                            <div class="card-body">
                                <a href="{% url 'blog:blog_detail' item.slug %}">
                                    <img alt="Изображение статьи" style="width: 75%"
                                         src="{% mediafile item.preview_image %} "/>
                                </a>
                                <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                                    <li>Содержание: {{ item.content|truncatechars:100 }}</li>
                                </ul>
                                <div class="d-flex justify-content-between align-items-center">
                                    <div class="btn-group">
                                        <a href="{% url 'blog:blog_detail' item.slug %}"
                                           class="btn btn-sm btn-outline-info text-dark">
                                            Подробно
                                        </a>
                                        {% if item.owner.email == user.email or 'Managers' in user_group_names %}
                                            <a href="{% url 'blog:blog_update' item.slug %}"
                                               class="btn btn-sm btn-outline-warning text-dark">
                                                Редактировать
                                            </a>
                                            <a href="{% url 'blog:blog_delete' item.slug %}"
                                               class="btn btn-sm btn-danger text-white">
                                                Удалить
                                            </a>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}