blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogPostListView, BlogPostDetailView, BlogPostCreateView, BlogPostUpdateView, BlogPostDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('', BlogPostListView.as_view(), name='blog_list'),
    path('detail/<slug>/', cache_page(60)(BlogPostDetailView.as_view()), name='blog_detail'),
    path('create/', BlogPostCreateView.as_view(), name='blog_create'),
    path('update/<slug>/', BlogPostUpdateView.as_view(), name='blog_update'),
    path('delete/<slug>/', BlogPostDeleteView.as_view(), name='blog_delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('client/', include('message_email.urls', namespace='client')),
    path('email/', include('message_email.urls', namespace='email')),
    path('users/', include('users.urls', namespace='users')),
    path("blog/", include("blog.urls", namespace="blog")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import UserLoginView, UserLogoutView, UserRegistrationCreateView, user_registration_success, \
    user_verification_view, UserProfileUpdateView

app_name = UsersConfig.name

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('registration/', UserRegistrationCreateView.as_view(), name='registration'),
    path('registration_success/', user_registration_success, name='registration_success'),
    path('verification/<int:pk>/<str:token>/', user_verification_view, name='verification'),
    path('profile/', UserProfileUpdateView.as_view(), name='profile')
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class User(AbstractUser):
    username = None

    email = models.EmailField(unique=True, verbose_name='почта')
    is_active = models.BooleanField(default=False, verbose_name='активен')

    verification_token = models.CharField(max_length=20, **NULLABLE, verbose_name='токен')
    phone = models.CharField(max_length=35, **NULLABLE, unique=True, verbose_name='телефон')
    avatar = models.ImageField(**NULLABLE, upload_to='app_user/avatar', verbose_name='аватар')
    country = models.CharField(**NULLABLE, max_length=150, verbose_name='страна')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

    class Meta:
        permissions = [
            ("Can_view_the_list_of_users_of_the_service", 'Can view the list of service users'),
            ("May_block_users_of_the_service", 'Can block users of the service'),
        ]
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

from .models import User


class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['email'].widget.attrs.update(
            {"class": "form-control", "placeholder": "Напишите ваш e-mail"})
        self.fields['password1'].widget.attrs.update(
            {"class": "form-control", "placeholder": "Новый пароль"})
        self.fields['password2'].widget.attrs.update(
            {"class": "form-control", "placeholder": "Повторите пароль"})

        for field_name in self.fields:
            self.fields[field_name].label = ""
            self.fields[field_name].help_text = ""


class UserLoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['username'].widget.attrs.update(
            {"class": "form-control", "placeholder": "Напишите ваш e-mail"})
        self.fields['password'].widget.attrs.update(
            {"class": "form-control", "placeholder": "Напишите ваш пароль"})

        for field_name in self.fields:
            self.fields[field_name].label = ""
            self.fields[field_name].help_text = ""


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'phone', 'avatar', 'country')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['first_name'].widget.attrs.update(
            {"class": "form-control", "placeholder": "Напишите ваше имя"})
        self.fields['last_name'].widget.attrs.update(
            {"class": "form-control", "placeholder": "Напишите вашу фамилию"})
        self.fields['phone'].widget.attrs.update(
            {"class": "form-control", "placeholder": "Напишите свой телефон"})
        self.fields['avatar'].widget.attrs.update(
            {"class": "form-control"})
        self.fields['country'].widget.attrs.update(
            {"class": "form-control", "placeholder": "Напишите вашу страну"})

        for field_name in self.fields:
            self.fields[field_name].label = ""
            self.fields[field_name].help_text = ""

users/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.views import LoginView as BaseLoginView
from django.contrib.auth.views import LogoutView as BaseLogoutView
from django.core.mail import send_mail
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView

from users.forms import UserLoginForm, UserRegistrationForm, UserProfileForm
from users.models import User
from users.services import generate_verification_token


class UserLoginView(BaseLoginView):
    model = User
    form_class = UserLoginForm
    template_name = 'users/login_form.html'
    success_url = reverse_lazy('home:index')

    def form_valid(self, form):
        user = form.get_user()

        if not user.is_active:
            messages.error(
                self.request,
                message='Ваша учетная запись не активирована. Пожалуйста, проверьте свою электронную почту.'
            )

        return super().form_valid(form)


class UserLogoutView(BaseLogoutView):
    pass


def user_registration_success(request):
    return render(request, template_name='users/registration_success.html')


def user_verification_view(request, pk, token):
    user = get_object_or_404(User, pk=pk, verification_token=token)
    user.is_active = True
    user.verification_token = None
    user.save()
    return redirect('users:login')


class UserRegistrationCreateView(CreateView):
    model = User
    form_class = UserRegistrationForm
    template_name = 'users/registration_form.html'
    success_url = reverse_lazy('users:registration_success')

    def form_valid(self, form):
        new_user = form.save()
        verification_token = generate_verification_token()
        new_user.verification_token = verification_token
        new_user.save()

        verification_url = self.request.build_absolute_uri(
            reverse(
                viewname='users:verification',
                args=[new_user.pk, verification_token])
        )

        send_mail(
            subject='Успешная регистрация на почтовом сервисе',
            message=f'Нажмите сюда, чтобы активировать свой профиль {verification_url}.',
            from_email=settings.DEFAULT_FROM_EMAIL,
            recipient_list=[new_user.email]
        )
        return super().form_valid(form)


class UserProfileUpdateView(UpdateView):
    model = User
    form_class = UserProfileForm
    template_name = 'users/profile_form.html'
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user

users/templates/users/login_form.html
{% extends 'home/base.html' %}

{% block content %}
    <div class="d-flex justify-content-center align-items-center h-50">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-6 col-md-8 col-sm-10">
                    <div class="card shadow-lg p-4">
                        <h4 class="text-center mb-4">Авторизоваться</h4>
                        <form method="post">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-outline-success w-100">Вход</button>
                            <br>
                            <br>
                            <p class="my-3 text-center">Еще не зарегистрированы?
                                <a href="{% url 'users:registration' %}"
                                   class="text-primary fw-bold">Создать аккаунт!</a></p>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

users/templates/users/profile_form.html
{% extends 'home/base.html' %}

{% block content %}
    <div class="d-flex justify-content-center align-items-center h-50">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-6 col-md-8 col-sm-10">
                    <div class="card shadow-lg p-4">
                        <h4 class="text-center mb-4">Профиль</h4>
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-sm btn-outline-secondary text-danger">Сохранить
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

users/templates/users/registration_form.html
{% extends 'home/base.html' %}

{% block content %}
    <div class="d-flex justify-content-center align-items-center h-50">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-6 col-md-8 col-sm-10">
                    <div class="card shadow-lg p-4">
                        <h4 class="text-center mb-4">Регистрация</h4>
                        <form method="post">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-sm btn-success text-white">
                                Зарегистрироваться
                            </button>
                            <br>
                            <br>
                            <p class="my-3 text-center">Если у вас есть аккаунт?
                                <a href="{% url 'users:login' %}"
                                   class="text-primary fw-bold">Вход!</a></p>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

users/templates/users/registration_success.html
{% extends 'home/base.html' %}

{% block content %}
<div class="d-flex justify-content-center align-items-center h-50">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-6 col-md-8 col-sm-10">
                <div class="card shadow-lg p-4">
                    <h4 class="text-center mb-4">
                        Проверь свою почту!
                    </h4>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}